volumes:
  ny_taxi_postgres_data:
    external: true

networks:
  pg_network:
    external: true

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi 
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    networks:
      - pg_network
    ports:
      - "5002:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - pg_network
    ports:
      - "8002:80"