version: 2

models:
  - name: stg_green_tripdata
    description: ""
    columns:
      - name: tripid
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      
      - name: pickup_locationid
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn
      
      - name: dropoff_locationid
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn
      
      - name: payment_type
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false